name:                HTPL-thesis
version:             0.1.0.0
github:              "githubuser/HTPL-thesis"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HTPL-thesis#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- megaparsec >= 9.2.2
- parser-combinators >= 1.3.0
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  HTPL-thesis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTPL-thesis
    - text
    - containers
    - megaparsec >= 9.2.2
    - parser-combinators >= 1.3.0

tests:
  HTPL-thesis-test:
    main:                ParserTests.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HTPL-thesis
    - tasty
    - tasty-hunit